# Generated by Django 2.2.13 on 2021-11-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20211105_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='jour',
        ),
    ]
