# Generated by Django 2.2.13 on 2021-11-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_event_contenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='inscrits',
        ),
    ]
