# Generated by Django 2.2.13 on 2021-11-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20211105_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='jour',
            new_name='du',
        ),
    ]
