# Generated by Django 2.2.13 on 2021-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_auto_20211105_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contenu',
            field=models.CharField(default='Non défini', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='inscrits',
            field=models.TextField(default='NOM Prénom Classe Groupe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prof',
            field=models.CharField(choices=[('SD7 | M. El Hammouchi', 'M. El Hammouchi'), ('SD8 | Mme. Lannes', 'Mme. Lannes'), ('SD9 | Mme. Kelly', 'Mme. Kelly'), ('Labo | Mme. Azam', 'Mme. Azam')], default='Non défini', max_length=200),
        ),
    ]
