# Generated by Django 2.2.13 on 2021-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_auto_20211106_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inscrits',
            field=models.TextField(default='Indiquez les informations suivantes :\nNOM Prénom Classe Groupe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prof',
            field=models.CharField(choices=[('SDL | Mme. Azam', 'Mme. Azam'), ('SD8 | Mme. Lannes', 'Mme. Lannes'), ('SD9 | Mme. Kelly', 'Mme. Kelly'), ('SD7 | M. El Hammouchi', 'M. El Hammouchi')], default='Non défini', max_length=200),
        ),
    ]
